### PR TITLE
Release/1.5.0

### PR DESCRIPTION
**Pull request by mauroservienti**
@micdenny please review and merge if good
Connected to https://github.com/RadicalFx/housekeeping/issues/57

Question: once this is merged should we:

* reverse merge from `master` to `develop`?
* rebase `develop` on `master`?
* merge this release branch to `develop` as well?

### CODE REVIEW

**Comment by mauroservienti** [comment]
Question: once this is merged should we:

* reverse merge from `master` to `develop`?
* rebase `develop` on `master`?
* merge this release branch to `develop` as well?

**Comment by micdenny** [comment]
> reverse merge from master to develop?
> rebase develop on master?

for sure a reverse merge that force a merge commit would be a shame and useless, so at least a merge without a PR that end-up in a fast-forward merge with no additional commit, or like you said a rebase, that actually is the same in case of ff merge.

> merge this release branch to develop as well?

is the same as merging from master unless in the meanwhile there were another commit in master, but anyway develop must be always aligned to master, so merge always everything from master to develop is a good way.

Another idea could be to avoid PR for releasing, just merge from git and gitversion will do the rest tagging the source, in this way you don't need a reverse merge at all, the history then is simply the same with an additional tag after the build, but in the history could be good to have a clear sign of the release.... what do you think? what others do?

**Comment by mauroservienti** [comment]
I'd prefer to have the release branch it might be useful to tweak the bits just for the release, and that should not block `develop` in any way.

I'll go with a `merge without a PR` after this is merged.
Feel free to merge as you like.
Once merged I'll proceed with all the downstream repos so that we'll bring `GitVersion` on all `master` branches as well.

**Comment by micdenny** [comment]
great! merging...

**Comment by mauroservienti** [comment]
Super, thanks.

**Pull request merged**
