### PR TITLE
Moved ShowIcon to WindowControlBoxBehavior

### PR DESCRIPTION
**Pull request by nazarenomanco**
@mauroservienti here it is

### CODE REVIEW

**Comment by mauroservienti** [comment]
@nazarenomanco if we drop code from the [WindowsManager](https://github.com/RadicalFx/Radical.Windows/pull/65/files#diff-e6bf4e0142faf9d7adbed5612224854c) class then it's a breaking change, and it requires a major release.

Instead of removing the code from the WindowsManager decorate public members with the `[Obsolete]` attribute. In the Obsolete message state that "The feature will be removed in the next major version, please use the new bla bla bla available in bla bla bla".
Also `TreatAsError` should be set to `false`.

**Comment by nazarenomanco** [comment]
@mauroservienti done! Please check

**Comment by mauroservienti** [comment]
@nazarenomanco add the `Obsolete` attribute on *all* the public members in [WindowsManager](https://github.com/RadicalFx/Radical.Windows/pull/65/files#diff-e6bf4e0142faf9d7adbed5612224854c)

I also saw a couple of bugs, not connected to this PR. As son as this is merged I'll raise issues.

**Comment by nazarenomanco** [comment]
@mauroservienti sorry 😊

**Pull request merged**
