### PR TITLE
Add scroll into view for listbox

### LINKED ISSUE #24: ScrollIntoView: ListBox
Allows to control the scroll position based on a element in the VM

### PR DESCRIPTION
**Pull request by nazarenomanco**
Fix #24 Connects to https://github.com/RadicalFx/Radical.Windows/issues/53

@mauroservienti please check. Do we have to do the same for Grid and ListView?

### CODE REVIEW

**Comment by mauroservienti** [comment]
@nazarenomanco this is ready to be merged but as expected now we have conflicts on the project file. Could you sync your fork, fix the conflict and push again? thanks.

**Comment by mauroservienti** [comment]
In any case wait for [this build](https://ci.appveyor.com/project/radical-bot/radical-windows/build/1.6.0-alpha.6.build.48) to be green.

**Comment by mauroservienti** [comment]
`develop` build is green again with the nuget fix in place. Go ahead 😄

**Comment by mauroservienti** [comment]
BTW:

> Do we have to do the same for Grid and ListView?

yes 😄 : #54 #55

**Comment by nazarenomanco** [comment]
@mauroservienti please check. I hope I do everything well

**Comment by mauroservienti** [comment]
it's OK. I'll merge.

**Pull request merged**
