### PR TITLE
AutoCommandBindings does not correctly bind if the VM method ends with "Command"

### LINKED ISSUE #3: AutoCommandBindings does not correctly bind if the VM method ends with "Command"
_From @mauroservienti on March 26, 2014 10:19_

_Copied from original issue: RadicalFx/Radical#48_

### PR DESCRIPTION
**Pull request by mauroservienti**
I finally found the time to have a look at this long time bug. The actual fix is designed to be backward compatible with 1.6.0, thus I'm proposing to release it as a hotfix against `master`. Once released we can backport it to `develop`.

@micdenny please review.

Connects to #3 
Fix #3

### CODE REVIEW

**Comment by mauroservienti** [comment]
Hold on, to be fully backward compatible the search for the method should work the other way round https://github.com/RadicalFx/Radical.Windows/blob/6bc78d903acae324db691c40d5d734fb416f2962/src/net35/Radical.Windows/Presentation/CommandBuilders/DelegateCommandBuilder.cs#L94

It should be as before, first if the methodName has the Command suffix we should remove the suffix and look for it, if nothing is found we should look with the suffix. Otherwise with there is no suffix we should perform only a single search as before.

This is because the previous buggy behavior was intended to let you write in the xaml `DoCommand` but in the view model simply have a `Do` method.

**Comment by micdenny** [comment]
should I wait then to review it, or it is ready for review?

**Comment by mauroservienti** [comment]
no, wait a second. I need to brainstorm a little bit to see if the order in which we pick up things might have some hidden breaking changes. I'll find time to do that today.

**Comment by mauroservienti** [comment]
@micdenny this is now ready for review, I did several different permutation locally and this is so far the best setup. IMO tests cover all the supported scenarios and are backward compatible as well.

Please take a closer look. Given that this affects run-time binding it's very easy to break end user code in very subtle way.

If we're not comfortable we can make this an opt-in or opt-out thing via a configuration setting, e.g.:

```
<add key="AutoCommandBindingBehavior" value="LegacyMode|Default" />
```

And then decide that the on proposed in this hotfix is the new `Default` and setting `LegacyMode` will revert back to the old one, if we don't document it we'll have issues raised (hopefully) that we can use as test cases to improve the default behavior at a point that in a major release we can drop the legacy one.

I'm not a big fun of this type of code branches but it's an option.

**Comment by micdenny** [comment]
I think we can go with just the new version, I don't see any particular advantages from keeping the `GetExpectedMethodName` that auto-magically do things, best to cut it off, and instead of having a configuration `AutoCommandBindingBehavior` is there a way to create a component that can be replaced at run-time on the container? So we can leave the old implementation, and if someone really needs it, it just replace the component in the container, I usually like the extension way of having all the components be replaceable from the container.

What do you think @mauroservienti ?

**Comment by mauroservienti** [comment]
As of now there is no easy or clean way to inject anything. The `AutoCommandBinding` is a markup extension so its lifecycle is fully managed by WPF. The only real option would be a service locator like thing via a static property. Thank you, but no unless it is strictly required, thank you 😉 

What about we this as is, with no settings at all to control the behavior. We merge, publish and wait. Tests cover all the permutations I could think of, if something bad happens we can always:

* add new tests and implement a fix as a patch
* add the settings and allow users to revert back to the old behavior in case it cannot be easily fixed

If you agree go ahead and merge, I'll take care of the release process.

**Comment by micdenny** [comment]
> If you agree go ahead and merge, I'll take care of the release process.

ok then 😄

**Comment by micdenny** [comment]
it should be released right-away because we've merge an hotfix branch, so gitversion should do it's job reading the commit message

**Comment by micdenny** [comment]
we just need to back merge on develop

**Comment by mauroservienti** [comment]
>we just need to back merge on develop

done

**Pull request merged**
